import type { Billboard, Campaign } from "./types";

export const campaigns: Campaign[] = [
  {
    id: "camp-001",
    name: "GTBank Season of Banking",
    advertiser: "Guaranty Trust Bank",
    product: "GTBank Mobile App",
    description: "Experience seamless banking at your fingertips with the GTBank mobile app. Transfer funds, pay bills, and manage your account 24/7.",
    startDate: "2024-11-01",
    endDate: "2025-03-31",
    budget: 12500000,
    targetUrl: "https://gtbank.com",
    creative: "Banking made simple. Download now.",
  },
  {
    id: "camp-002",
    name: "MTN Momo Drive",
    advertiser: "MTN Nigeria",
    product: "MoMo PSB",
    description: "Send money, pay bills, and shop with ease using MTN MoMo. No bank account needed — just your SIM card.",
    startDate: "2024-12-01",
    endDate: "2025-04-30",
    budget: 18000000,
    targetUrl: "https://mtn.com.ng/momo",
    creative: "Move money freely. MTN MoMo.",
  },
  {
    id: "camp-003",
    name: "Dangote Pasta Pride",
    advertiser: "Dangote Group",
    product: "Dangote Pasta",
    description: "Quality pasta made from the finest durum wheat. Dangote Pasta — the taste your family deserves.",
    startDate: "2025-01-01",
    endDate: "2025-06-30",
    budget: 8000000,
    targetUrl: "https://dangote.com",
    creative: "Family meals, Nigerian quality.",
  },
  {
    id: "camp-004",
    name: "Indomie Noodle Nation",
    advertiser: "Dufil Prima Foods",
    product: "Indomie Noodles",
    description: "Indomie — the noodle that Nigeria loves. Quick, delicious, and made for every Nigerian.",
    startDate: "2024-10-15",
    endDate: "2025-03-15",
    budget: 22000000,
    targetUrl: "https://indomie.com.ng",
    creative: "Naija's favourite noodle. Indomie!",
  },
  {
    id: "camp-005",
    name: "Airtel Broadband Push",
    advertiser: "Airtel Nigeria",
    product: "Airtel 5G Data Plans",
    description: "Superfast 5G internet from Airtel. Stream, game, and work without limits.",
    startDate: "2025-01-15",
    endDate: "2025-07-15",
    budget: 15000000,
    targetUrl: "https://airtel.com.ng",
    creative: "5G is here. Experience it now.",
  },
  {
    id: "camp-006",
    name: "PalmPay Cashback Promo",
    advertiser: "PalmPay",
    product: "PalmPay Wallet",
    description: "Earn cashback on every transaction. Download PalmPay and enjoy instant rewards.",
    startDate: "2025-02-01",
    endDate: "2025-05-31",
    budget: 9500000,
    targetUrl: "https://palmpay.com",
    creative: "Pay smart. Earn cashback daily.",
  },
  {
    id: "camp-007",
    name: "Chicken Republic Fest",
    advertiser: "Chicken Republic",
    product: "Family Meal Deals",
    description: "Bring the family together with Chicken Republic's mega meal deals. Crispy chicken, great value.",
    startDate: "2024-12-15",
    endDate: "2025-02-28",
    budget: 6000000,
    targetUrl: "https://chickenrepublic.com",
    creative: "Crispy. Juicy. Family approved.",
  },
  {
    id: "camp-008",
    name: "FCMB Back to School",
    advertiser: "First City Monument Bank",
    product: "FCMB Education Loan",
    description: "Invest in the future. FCMB Education Loans with flexible repayment plans for every Nigerian family.",
    startDate: "2025-01-05",
    endDate: "2025-04-05",
    budget: 7500000,
    targetUrl: "https://fcmb.com",
    creative: "Education changes lives. FCMB is with you.",
  },
];

export const billboards: Billboard[] = [
  {
    id: "billboard-001",
    name: "Third Mainland Bridge Approach",
    location: "Third Mainland Bridge, Lagos Island",
    city: "Lagos",
    coordinates: { lat: 6.4698, lng: 3.3965 },
    campaign: campaigns[0],
    status: "active",
    size: "48ft × 14ft",
    dailyTraffic: 285000,
    installedDate: "2023-06-15",
  },
  {
    id: "billboard-002",
    name: "Lekki-Epe Expressway (Admiralty)",
    location: "Admiralty Way Junction, Lekki Phase 1, Lagos",
    city: "Lagos",
    coordinates: { lat: 6.4302, lng: 3.4702 },
    campaign: campaigns[1],
    status: "active",
    size: "36ft × 12ft",
    dailyTraffic: 198000,
    installedDate: "2023-09-20",
  },
  {
    id: "billboard-003",
    name: "Victoria Island Ozumba Mbadiwe",
    location: "Ozumba Mbadiwe Avenue, Victoria Island, Lagos",
    city: "Lagos",
    coordinates: { lat: 6.4281, lng: 3.4219 },
    campaign: campaigns[2],
    status: "active",
    size: "40ft × 14ft",
    dailyTraffic: 165000,
    installedDate: "2023-08-01",
  },
  {
    id: "billboard-004",
    name: "Allen Avenue Ikeja",
    location: "Allen Avenue, Ikeja, Lagos",
    city: "Lagos",
    coordinates: { lat: 6.6018, lng: 3.3515 },
    campaign: campaigns[3],
    status: "active",
    size: "32ft × 10ft",
    dailyTraffic: 220000,
    installedDate: "2023-11-10",
  },
  {
    id: "billboard-005",
    name: "Abuja Airport Road",
    location: "Nnamdi Azikiwe International Airport Road, Abuja",
    city: "Abuja",
    coordinates: { lat: 9.0068, lng: 7.2631 },
    campaign: campaigns[4],
    status: "active",
    size: "48ft × 16ft",
    dailyTraffic: 142000,
    installedDate: "2023-07-25",
  },
  {
    id: "billboard-006",
    name: "Wuse II Central Business",
    location: "Aminu Kano Crescent, Wuse II, Abuja",
    city: "Abuja",
    coordinates: { lat: 9.0765, lng: 7.4898 },
    campaign: campaigns[5],
    status: "active",
    size: "36ft × 12ft",
    dailyTraffic: 98000,
    installedDate: "2024-01-15",
  },
  {
    id: "billboard-007",
    name: "Maitama Diplomatic Drive",
    location: "Aguiyi Ironsi Street, Maitama, Abuja",
    city: "Abuja",
    coordinates: { lat: 9.0814, lng: 7.4951 },
    campaign: campaigns[6],
    status: "active",
    size: "30ft × 10ft",
    dailyTraffic: 72000,
    installedDate: "2024-02-20",
  },
  {
    id: "billboard-008",
    name: "Lagos-Ibadan Expressway (Berger)",
    location: "Berger Junction, Lagos-Ibadan Expressway, Lagos",
    city: "Lagos",
    coordinates: { lat: 6.6385, lng: 3.3613 },
    campaign: campaigns[7],
    status: "active",
    size: "48ft × 14ft",
    dailyTraffic: 310000,
    installedDate: "2023-05-10",
  },
];
